<a href="https://colab.research.google.com/github/isaacye/SS2020_ML_Day2/blob/master/Session_1/Lab0_toy_pyTorch_grad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
print(torch.__version__)

N, D = 3, 4

#x = torch.ones(N,D)
x = torch.ones(N,D, requires_grad=True)
y = 2*torch.ones(N,D)
z = 3*torch.ones(N,D)

1.5.0+cu101


In [0]:
print(x)
print(y)
print(z)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [0]:
a = x*y
b = a+z
c = torch.sum(b)
print(c)

tensor(60., grad_fn=<SumBackward0>)


In [0]:
c.backward()
print(x.grad)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
