In [2]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.2.0


In [0]:
N, D = 3, 4

x = tf.ones([N,D])
y = 2*tf.ones([N, D])
z = 3*tf.ones([N, D])

In [8]:
print(x)
print(y)
print(z)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(3, 4), dtype=float32)


In [17]:
with tf.GradientTape(persistent=True) as g:
  g.watch(x)
  a = x * y
  b = a + z
  c = tf.reduce_sum(b)
grad_x = g.gradient(b,x)
print(c)
print(grad_x)

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]], shape=(3, 4), dtype=float32)
