In [7]:
import torch
print(torch.__version__)

N, D = 3, 4

#x = torch.ones(N,D)
x = torch.ones(N,D, requires_grad=True)
y = 2*torch.ones(N,D)
z = 3*torch.ones(N,D)

1.5.0+cu101


In [8]:
print(x)
print(y)
print(z)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [9]:
a = x*y
b = a+z
c = torch.sum(b)
print(c)

tensor(60., grad_fn=<SumBackward0>)


In [10]:
c.backward()
print(x.grad)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
