<a href="https://colab.research.google.com/github/isaacye/SS2020_ML_Day2/blob/master/Session_1/Lab1_numpy_grad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
np.random.seed(0)

N, D = 3, 4

x = np.ones((N,D))
y = 2*np.ones((N,D))
z = 3*np.ones((N,D))

In [0]:
print(x)
print(y)
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [0]:
a = x * y
b = a + z
c = np.sum(b)
print(c)

60.0


In [0]:
grad_c = 1.0
grad_b = grad_c * np.ones((N,D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()

grad_x = grad_a*y
grad_y = grad_a*x

In [0]:
print(grad_x)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
